name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10.13'  # Specify the desired Python version
        cache: 'pip'  # Specify the package manager for caching
        architecture: 'x64'  # Specify the target architecture

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy model
      run: |
        mlflow.pyfunc.serve --model-uri model
